
server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
  mvc:
    date-format: yyyy-MM-dd

mybatis:
  type-aliases-package: com.qf.demo.pojo
  mapper-locations: classpath*:mapping/*.xml

pagehelper:
  auto-dialect: mysql


